// Course categories and data
export const courseCategories = {
    htmlCss: 'HTML & CSS',
    javascript: 'JavaScript',
    typescript: 'TypeScript',
    python: 'Python',
    react: 'React',
    vue: 'Vue.js',
    angular: 'Angular',
    node: 'Node.js',
    express: 'Express.js',
    nextjs: 'Next.js',
    flask: 'Flask',
    django: 'Django',
    fastapi: 'FastAPI',
    fullstack: 'Full Stack',
    databases: 'Databases',
    mongodb: 'MongoDB',
    sql: 'SQL',
    graphql: 'GraphQL',
    git: 'Git & Version Control',
    docker: 'Docker & Kubernetes',
    aws: 'AWS & Cloud',
    devops: 'DevOps',
    testing: 'Testing',
    go: 'Go Language',
    rust: 'Rust',
    java: 'Java',
    spring: 'Spring Boot',
    csharp: 'C# & .NET',
    php: 'PHP',
    laravel: 'Laravel',
    ruby: 'Ruby on Rails',
    swift: 'Swift/iOS',
    kotlin: 'Kotlin/Android',
    flutter: 'Flutter',
    reactNative: 'React Native',
    machineLearning: 'Machine Learning',
    dataScience: 'Data Science',
    cybersecurity: 'Cybersecurity',
    blockchain: 'Blockchain',
    wordpress: 'WordPress',
    seo: 'SEO & Digital Marketing'
};

export const coursesData = [
    // HTML & CSS Courses (5 courses)
    {
        id: 1,
        category: courseCategories.htmlCss,
        courseName: 'HTML & CSS Full Course 2024',
        tutor: 'SuperSimpleDev',
        duration: '6.5 hours',
        level: 'Beginner',
        description: 'Learn HTML and CSS from scratch with practical projects. Build responsive websites.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/G3e-cpL7ofc',
        externalUrl: 'https://www.youtube.com/watch?v=G3e-cpL7ofc',
        thumbnail: 'https://img.youtube.com/vi/G3e-cpL7ofc/maxresdefault.jpg',
        rating: 4.8,
        students: '1.2M+',
        language: 'English',
        paid: false
    },
    {
        id: 2,
        category: courseCategories.htmlCss,
        courseName: 'CSS Tutorial - Zero to Hero',
        tutor: 'freeCodeCamp',
        duration: '6 hours',
        level: 'Beginner to Intermediate',
        description: 'Complete CSS course covering selectors, flexbox, grid, animations, and responsive design.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/1Rs2ND1ryYc',
        externalUrl: 'https://www.youtube.com/watch?v=1Rs2ND1ryYc',
        thumbnail: 'https://img.youtube.com/vi/1Rs2ND1ryYc/maxresdefault.jpg',
        rating: 4.8,
        students: '3M+',
        language: 'English',
        paid: false
    },
    {
        id: 3,
        category: courseCategories.htmlCss,
        courseName: 'HTML & CSS Tutorial for Beginners',
        tutor: 'freeCodeCamp',
        duration: '11 hours',
        level: 'Beginner',
        description: 'Comprehensive HTML and CSS tutorial building multiple projects.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/mU6anWqZJcc',
        externalUrl: 'https://www.youtube.com/watch?v=mU6anWqZJcc',
        thumbnail: 'https://img.youtube.com/vi/mU6anWqZJcc/maxresdefault.jpg',
        rating: 4.8,
        students: '3M+',
        language: 'English',
        paid: false
    },
    {
        id: 4,
        category: courseCategories.htmlCss,
        courseName: 'Tailwind CSS Crash Course',
        tutor: 'Traversy Media',
        duration: '2 hours',
        level: 'Intermediate',
        description: 'Learn Tailwind CSS utility-first framework by building projects.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/dFgzHOX84xQ',
        externalUrl: 'https://www.youtube.com/watch?v=dFgzHOX84xQ',
        thumbnail: 'https://img.youtube.com/vi/dFgzHOX84xQ/maxresdefault.jpg',
        rating: 4.7,
        students: '500K+',
        language: 'English',
        paid: false
    },
    {
        id: 5,
        category: courseCategories.htmlCss,
        courseName: 'CSS Flexbox & Grid Masterclass',
        tutor: 'Web Dev Simplified',
        duration: '3 hours',
        level: 'Intermediate',
        description: 'Master CSS layouts with Flexbox and Grid through practical examples.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/JJSoEo8JSnc',
        externalUrl: 'https://www.youtube.com/watch?v=JJSoEo8JSnc',
        thumbnail: 'https://img.youtube.com/vi/JJSoEo8JSnc/maxresdefault.jpg',
        rating: 4.9,
        students: '800K+',
        language: 'English',
        paid: false
    },

    // JavaScript Courses (8 courses)
    {
        id: 6,
        category: courseCategories.javascript,
        courseName: 'JavaScript Full Course (2024)',
        tutor: 'SuperSimpleDev',
        duration: '12 hours',
        level: 'Beginner to Intermediate',
        description: 'Complete JavaScript course covering fundamentals to advanced concepts with projects.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/EerdGm-ehJQ',
        externalUrl: 'https://www.youtube.com/watch?v=EerdGm-ehJQ',
        thumbnail: 'https://img.youtube.com/vi/EerdGm-ehJQ/maxresdefault.jpg',
        rating: 4.9,
        students: '2.5M+',
        language: 'English',
        paid: false
    },
    {
        id: 7,
        category: courseCategories.javascript,
        courseName: 'The Complete JavaScript Course',
        tutor: 'Jonas Schmedtmann',
        duration: '68 hours',
        level: 'Beginner to Advanced',
        description: 'Modern JavaScript from beginner to advanced with 20+ projects.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/2Ji-clqUYnA',
        externalUrl: 'https://www.udemy.com/course/the-complete-javascript-course/',
        thumbnail: 'https://img.youtube.com/vi/2Ji-clqUYnA/maxresdefault.jpg',
        rating: 4.9,
        students: '800K+',
        language: 'English',
        paid: true
    },
    {
        id: 8,
        category: courseCategories.javascript,
        courseName: 'JavaScript Algorithms and Data Structures',
        tutor: 'freeCodeCamp',
        duration: '40 hours',
        level: 'Intermediate',
        description: 'Master JavaScript algorithms, data structures, and problem-solving.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/t2CEgPsws3U',
        externalUrl: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/',
        thumbnail: 'https://img.youtube.com/vi/t2CEgPsws3U/maxresdefault.jpg',
        rating: 4.9,
        students: '2M+',
        language: 'English',
        paid: false
    },
    {
        id: 9,
        category: courseCategories.javascript,
        courseName: 'ES6 JavaScript Tutorial',
        tutor: 'The Net Ninja',
        duration: '3 hours',
        level: 'Intermediate',
        description: 'Modern JavaScript features from ES6 to ES2024 with practical examples.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/NCwa_xi0Uuc',
        externalUrl: 'https://www.youtube.com/watch?v=NCwa_xi0Uuc',
        thumbnail: 'https://img.youtube.com/vi/NCwa_xi0Uuc/maxresdefault.jpg',
        rating: 4.8,
        students: '1M+',
        language: 'English',
        paid: false
    },
    {
        id: 10,
        category: courseCategories.javascript,
        courseName: 'JavaScript DOM Manipulation',
        tutor: 'Traversy Media',
        duration: '2 hours',
        level: 'Beginner',
        description: 'Learn to manipulate the DOM with vanilla JavaScript.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/5fb2aPlgoys',
        externalUrl: 'https://www.youtube.com/watch?v=5fb2aPlgoys',
        thumbnail: 'https://img.youtube.com/vi/5fb2aPlgoys/maxresdefault.jpg',
        rating: 4.8,
        students: '600K+',
        language: 'English',
        paid: false
    },
    {
        id: 11,
        category: courseCategories.javascript,
        courseName: 'Async JavaScript Crash Course',
        tutor: 'Web Dev Simplified',
        duration: '1.5 hours',
        level: 'Intermediate',
        description: 'Master async JavaScript: callbacks, promises, and async/await.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/V_Kr9OSfDeU',
        externalUrl: 'https://www.youtube.com/watch?v=V_Kr9OSfDeU',
        thumbnail: 'https://img.youtube.com/vi/V_Kr9OSfDeU/maxresdefault.jpg',
        rating: 4.9,
        students: '700K+',
        language: 'English',
        paid: false
    },
    {
        id: 12,
        category: courseCategories.javascript,
        courseName: 'Object-Oriented JavaScript',
        tutor: 'Mosh Hamedani',
        duration: '4 hours',
        level: 'Intermediate',
        description: 'Deep dive into OOP concepts in JavaScript with practical examples.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/PFmuCDHHpwk',
        externalUrl: 'https://codewithmosh.com/p/object-oriented-programming-in-javascript',
        thumbnail: 'https://img.youtube.com/vi/PFmuCDHHpwk/maxresdefault.jpg',
        rating: 4.8,
        students: '300K+',
        language: 'English',
        paid: true
    },
    {
        id: 13,
        category: courseCategories.javascript,
        courseName: 'JavaScript Design Patterns',
        tutor: 'Fireship',
        duration: '2 hours',
        level: 'Advanced',
        description: 'Learn essential JavaScript design patterns with real-world examples.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/tv-_1er1mWI',
        externalUrl: 'https://www.youtube.com/watch?v=tv-_1er1mWI',
        thumbnail: 'https://img.youtube.com/vi/tv-_1er1mWI/maxresdefault.jpg',
        rating: 4.7,
        students: '400K+',
        language: 'English',
        paid: false
    },

    // TypeScript Courses (4 courses)
    {
        id: 14,
        category: courseCategories.typescript,
        courseName: 'TypeScript Full Course',
        tutor: 'Codevolution',
        duration: '5 hours',
        level: 'Intermediate',
        description: 'Complete TypeScript course from basics to advanced with React integration.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/gieEQFIfgYc',
        externalUrl: 'https://www.youtube.com/watch?v=gieEQFIfgYc',
        thumbnail: 'https://img.youtube.com/vi/gieEQFIfgYc/maxresdefault.jpg',
        rating: 4.8,
        students: '400K+',
        language: 'English',
        paid: false
    },
    {
        id: 15,
        category: courseCategories.typescript,
        courseName: 'Understanding TypeScript',
        tutor: 'Maximilian Schwarzmüller',
        duration: '21 hours',
        level: 'Beginner to Advanced',
        description: 'Deep dive into TypeScript with React, Node.js, and real projects.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/2pZmKW9-I_k',
        externalUrl: 'https://www.udemy.com/course/understanding-typescript/',
        thumbnail: 'https://img.youtube.com/vi/2pZmKW9-I_k/maxresdefault.jpg',
        rating: 4.9,
        students: '200K+',
        language: 'English',
        paid: true
    },
    {
        id: 16,
        category: courseCategories.typescript,
        courseName: 'TypeScript for Beginners',
        tutor: 'Programming with Mosh',
        duration: '3 hours',
        level: 'Beginner',
        description: 'Get started with TypeScript and its core concepts.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/d56mG7DezGs',
        externalUrl: 'https://www.youtube.com/watch?v=d56mG7DezGs',
        thumbnail: 'https://img.youtube.com/vi/d56mG7DezGs/maxresdefault.jpg',
        rating: 4.8,
        students: '500K+',
        language: 'English',
        paid: false
    },
    {
        id: 17,
        category: courseCategories.typescript,
        courseName: 'Advanced TypeScript',
        tutor: 'Matt Pocock',
        duration: '6 hours',
        level: 'Advanced',
        description: 'Master advanced TypeScript patterns, generics, and type gymnastics.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/xsnEw8XOPc0',
        externalUrl: 'https://www.totaltypescript.com/',
        thumbnail: 'https://img.youtube.com/vi/xsnEw8XOPc0/maxresdefault.jpg',
        rating: 4.9,
        students: '150K+',
        language: 'English',
        paid: true
    },

    // Python Courses (8 courses)
    {
        id: 18,
        category: courseCategories.python,
        courseName: 'Python for Beginners',
        tutor: 'Code with Mosh',
        duration: '6 hours',
        level: 'Beginner',
        description: 'Learn Python programming from scratch with practical examples and exercises.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/rfscVS0vtbw',
        externalUrl: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
        thumbnail: 'https://img.youtube.com/vi/rfscVS0vtbw/maxresdefault.jpg',
        rating: 4.8,
        students: '3M+',
        language: 'English',
        paid: false
    },
    {
        id: 19,
        category: courseCategories.python,
        courseName: 'Python Full Course for Beginners',
        tutor: 'freeCodeCamp',
        duration: '12 hours',
        level: 'Beginner to Intermediate',
        description: 'Comprehensive Python course covering everything from basics to intermediate concepts with projects.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/_uQrJ0TkZlc',
        externalUrl: 'https://www.youtube.com/watch?v=_uQrJ0TkZlc',
        thumbnail: 'https://img.youtube.com/vi/_uQrJ0TkZlc/maxresdefault.jpg',
        rating: 4.9,
        students: '150K+',
        language: 'English',
        paid: true
    },
    {
        id: 20,
        category: courseCategories.python,
        courseName: 'Python for Everybody',
        tutor: 'Dr. Charles Severance',
        duration: '14 hours',
        level: 'Beginner',
        description: 'University of Michigan\'s Python course - learn to program and analyze data.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/8DvywoWv6fI',
        externalUrl: 'https://www.coursera.org/specializations/python',
        thumbnail: 'https://img.youtube.com/vi/8DvywoWv6fI/maxresdefault.jpg',
        rating: 4.9,
        students: '2M+',
        language: 'English',
        paid: false
    },
    {
        id: 21,
        category: courseCategories.python,
        courseName: 'Python Automation',
        tutor: 'freeCodeCamp',
        duration: '8 hours',
        level: 'Intermediate',
        description: 'Learn to automate tasks with Python - web scraping, APIs, and file handling.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/PXMJ6FS-dll',
        externalUrl: 'https://www.youtube.com/watch?v=PXMJ6FS-dll',
        thumbnail: 'https://img.youtube.com/vi/PXMJ6FS-dll/maxresdefault.jpg',
        rating: 4.8,
        students: '600K+',
        language: 'English',
        paid: false
    },
    {
        id: 22,
        category: courseCategories.python,
        courseName: 'Data Structures in Python',
        tutor: 'freeCodeCamp',
        duration: '6 hours',
        level: 'Intermediate',
        description: 'Master data structures and algorithms implementation in Python.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/pkYVOmU3MgA',
        externalUrl: 'https://www.youtube.com/watch?v=pkYVOmU3MgA',
        thumbnail: 'https://img.youtube.com/vi/pkYVOmU3MgA/maxresdefault.jpg',
        rating: 4.8,
        students: '500K+',
        language: 'English',
        paid: false
    },
    {
        id: 23,
        category: courseCategories.python,
        courseName: 'Python OOP Masterclass',
        tutor: 'Tim Buchalka',
        duration: '30 hours',
        level: 'Intermediate',
        description: 'Comprehensive object-oriented programming course in Python.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/WR8oDk3F-7U',
        externalUrl: 'https://www.udemy.com/course/python-object-oriented-programming/',
        thumbnail: 'https://img.youtube.com/vi/WR8oDk3F-7U/maxresdefault.jpg',
        rating: 4.7,
        students: '100K+',
        language: 'English',
        paid: true
    },
    {
        id: 24,
        category: courseCategories.python,
        courseName: 'Python for Data Analysis',
        tutor: 'freeCodeCamp',
        duration: '9 hours',
        level: 'Intermediate',
        description: 'Learn data analysis with Python using Pandas, NumPy, and Matplotlib.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/r-uOLxNrNk8',
        externalUrl: 'https://www.youtube.com/watch?v=r-uOLxNrNk8',
        thumbnail: 'https://img.youtube.com/vi/r-uOLxNrNk8/maxresdefault.jpg',
        rating: 4.9,
        students: '1M+',
        language: 'English',
        paid: false
    },
    {
        id: 25,
        category: courseCategories.python,
        courseName: 'Web Scraping with Python',
        tutor: 'Corey Schafer',
        duration: '3 hours',
        level: 'Intermediate',
        description: 'Learn to scrape websites using BeautifulSoup and Scrapy.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/XVv6mJpFOb0',
        externalUrl: 'https://www.youtube.com/watch?v=XVv6mJpFOb0',
        thumbnail: 'https://img.youtube.com/vi/XVv6mJpFOb0/maxresdefault.jpg',
        rating: 4.8,
        students: '400K+',
        language: 'English',
        paid: false
    },

    // React Courses (6 courses)
    {
        id: 26,
        category: courseCategories.react,
        courseName: 'React Full Course 2024',
        tutor: 'SuperSimpleDev',
        duration: '10 hours',
        level: 'Intermediate',
        description: 'Complete React course with hooks, context, redux, and real projects.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/xnSoyDGD-UI',
        externalUrl: 'https://www.youtube.com/watch?v=xnSoyDGD-UI',
        thumbnail: 'https://img.youtube.com/vi/xnSoyDGD-UI/maxresdefault.jpg',
        rating: 4.8,
        students: '500K+',
        language: 'English',
        paid: false
    },
    {
        id: 27,
        category: courseCategories.react,
        courseName: 'React - The Complete Guide',
        tutor: 'Maximilian Schwarzmüller',
        duration: '40 hours',
        level: 'Beginner to Advanced',
        description: 'Dive into React with hooks, Next.js, Redux, and over 15 projects.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/AC7I9C_jlwI',
        externalUrl: 'https://www.udemy.com/course/react-the-complete-guide-incl-redux/',
        thumbnail: 'https://img.youtube.com/vi/AC7I9C_jlwI/maxresdefault.jpg',
        rating: 4.9,
        students: '700K+',
        language: 'English',
        paid: true
    },
    {
        id: 28,
        category: courseCategories.react,
        courseName: 'React Hooks Tutorial',
        tutor: 'Codevolution',
        duration: '4 hours',
        level: 'Intermediate',
        description: 'Master all React hooks with practical examples.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/LlvBzyy-558',
        externalUrl: 'https://www.youtube.com/watch?v=LlvBzyy-558',
        thumbnail: 'https://img.youtube.com/vi/LlvBzyy-558/maxresdefault.jpg',
        rating: 4.9,
        students: '800K+',
        language: 'English',
        paid: false
    },
    {
        id: 29,
        category: courseCategories.react,
        courseName: 'Redux Toolkit Course',
        tutor: 'Laith Harb',
        duration: '3 hours',
        level: 'Intermediate',
        description: 'Learn state management with Redux Toolkit in React.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/NqzdVN2tyvQ',
        externalUrl: 'https://www.youtube.com/watch?v=NqzdVN2tyvQ',
        thumbnail: 'https://img.youtube.com/vi/NqzdVN2tyvQ/maxresdefault.jpg',
        rating: 4.7,
        students: '200K+',
        language: 'English',
        paid: false
    },
    {
        id: 30,
        category: courseCategories.react,
        courseName: 'React Testing Masterclass',
        tutor: 'The Net Ninja',
        duration: '5 hours',
        level: 'Advanced',
        description: 'Comprehensive guide to testing React applications with Jest and RTL.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/7dTTFW7yACQ',
        externalUrl: 'https://www.youtube.com/watch?v=7dTTFW7yACQ',
        thumbnail: 'https://img.youtube.com/vi/7dTTFW7yACQ/maxresdefault.jpg',
        rating: 4.8,
        students: '150K+',
        language: 'English',
        paid: false
    },
    {
        id: 31,
        category: courseCategories.react,
        courseName: 'React Performance Optimization',
        tutor: 'Fireship',
        duration: '2 hours',
        level: 'Advanced',
        description: 'Techniques to optimize React application performance.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/5fLW5Q5ODiE',
        externalUrl: 'https://www.youtube.com/watch?v=5fLW5Q5ODiE',
        thumbnail: 'https://img.youtube.com/vi/5fLW5Q5ODiE/maxresdefault.jpg',
        rating: 4.8,
        students: '300K+',
        language: 'English',
        paid: false
    },

    // Vue.js Courses (4 courses)
    {
        id: 32,
        category: courseCategories.vue,
        courseName: 'Vue.js 3 Full Course',
        tutor: 'The Net Ninja',
        duration: '12 hours',
        level: 'Beginner to Advanced',
        description: 'Complete Vue.js 3 course covering composition API, Vuex, and routing.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/YrxBCBibVo0',
        externalUrl: 'https://www.youtube.com/watch?v=YrxBCBibVo0',
        thumbnail: 'https://img.youtube.com/vi/YrxBCBibVo0/maxresdefault.jpg',
        rating: 4.9,
        students: '600K+',
        language: 'English',
        paid: false
    },
    {
        id: 33,
        category: courseCategories.vue,
        courseName: 'Vue.js - The Complete Guide',
        tutor: 'Maximilian Schwarzmüller',
        duration: '35 hours',
        level: 'Beginner to Advanced',
        description: 'Master Vue.js with composition API, Vuex, and Firebase integration.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/4deVCNJq3qc',
        externalUrl: 'https://www.udemy.com/course/vuejs-2-the-complete-guide/',
        thumbnail: 'https://img.youtube.com/vi/4deVCNJq3qc/maxresdefault.jpg',
        rating: 4.9,
        students: '300K+',
        language: 'English',
        paid: true
    },
    {
        id: 34,
        category: courseCategories.vue,
        courseName: 'Vue 3 Composition API',
        tutor: 'Laith Harb',
        duration: '2.5 hours',
        level: 'Intermediate',
        description: 'Deep dive into Vue 3 Composition API and reusable composables.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/bwItcaoxd5E',
        externalUrl: 'https://www.youtube.com/watch?v=bwItcaoxd5E',
        thumbnail: 'https://img.youtube.com/vi/bwItcaoxd5E/maxresdefault.jpg',
        rating: 4.7,
        students: '150K+',
        language: 'English',
        paid: false
    },
    {
        id: 35,
        category: courseCategories.vue,
        courseName: 'Vuex State Management',
        tutor: 'The Net Ninja',
        duration: '3 hours',
        level: 'Intermediate',
        description: 'Learn state management in Vue with Vuex and Pinia.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/5lVQgZzLMHc',
        externalUrl: 'https://www.youtube.com/watch?v=5lVQgZzLMHc',
        thumbnail: 'https://img.youtube.com/vi/5lVQgZzLMHc/maxresdefault.jpg',
        rating: 4.8,
        students: '250K+',
        language: 'English',
        paid: false
    },

    // Node.js Courses (5 courses)
    {
        id: 36,
        category: courseCategories.node,
        courseName: 'Node.js Full Course for Beginners',
        tutor: 'freeCodeCamp',
        duration: '8 hours',
        level: 'Intermediate',
        description: 'Build scalable backend applications with Node.js, Express, and MongoDB.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/TlB_eWDSMt4',
        externalUrl: 'https://www.youtube.com/watch?v=TlB_eWDSMt4',
        thumbnail: 'https://img.youtube.com/vi/TlB_eWDSMt4/maxresdefault.jpg',
        rating: 4.8,
        students: '800K+',
        language: 'English',
        paid: false
    },
    {
        id: 37,
        category: courseCategories.node,
        courseName: 'Node.js - The Complete Guide',
        tutor: 'Maximilian Schwarzmüller',
        duration: '40 hours',
        level: 'Beginner to Advanced',
        description: 'Master Node.js with Express, MongoDB, GraphQL, and building REST APIs.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/Oe421EPjeBE',
        externalUrl: 'https://www.udemy.com/course/nodejs-the-complete-guide/',
        thumbnail: 'https://img.youtube.com/vi/Oe421EPjeBE/maxresdefault.jpg',
        rating: 4.9,
        students: '400K+',
        language: 'English',
        paid: true
    },
    {
        id: 38,
        category: courseCategories.node,
        courseName: 'Node.js API Masterclass',
        tutor: 'Traversy Media',
        duration: '10 hours',
        level: 'Intermediate',
        description: 'Build a production-ready Node.js API with Express and MongoDB.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/_M7GikW3jg0',
        externalUrl: 'https://www.youtube.com/watch?v=_M7GikW3jg0',
        thumbnail: 'https://img.youtube.com/vi/_M7GikW3jg0/maxresdefault.jpg',
        rating: 4.8,
        students: '350K+',
        language: 'English',
        paid: false
    },
    {
        id: 39,
        category: courseCategories.node,
        courseName: 'Advanced Node.js',
        tutor: 'Hussein Nasser',
        duration: '5 hours',
        level: 'Advanced',
        description: 'Deep dive into Node.js internals, event loop, and performance optimization.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/ENrzD9HAZK4',
        externalUrl: 'https://www.youtube.com/watch?v=ENrzD9HAZK4',
        thumbnail: 'https://img.youtube.com/vi/ENrzD9HAZK4/maxresdefault.jpg',
        rating: 4.8,
        students: '200K+',
        language: 'English',
        paid: false
    },
    {
        id: 40,
        category: courseCategories.node,
        courseName: 'Node.js Authentication',
        tutor: 'Web Dev Simplified',
        duration: '2 hours',
        level: 'Intermediate',
        description: 'Implement JWT authentication and authorization in Node.js.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/mbsmsi7l3r4',
        externalUrl: 'https://www.youtube.com/watch?v=mbsmsi7l3r4',
        thumbnail: 'https://img.youtube.com/vi/mbsmsi7l3r4/maxresdefault.jpg',
        rating: 4.9,
        students: '450K+',
        language: 'English',
        paid: false
    },

    // Next.js Courses (4 courses)
    {
        id: 41,
        category: courseCategories.nextjs,
        courseName: 'Next.js 14 Full Course',
        tutor: 'JavaScript Mastery',
        duration: '8 hours',
        level: 'Intermediate',
        description: 'Build modern full-stack applications with Next.js 14, App Router, and Server Actions.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/9P8mASSREYM',
        externalUrl: 'https://www.youtube.com/watch?v=9P8mASSREYM',
        thumbnail: 'https://img.youtube.com/vi/9P8mASSREYM/maxresdefault.jpg',
        rating: 4.9,
        students: '300K+',
        language: 'English',
        paid: false
    },
    {
        id: 42,
        category: courseCategories.nextjs,
        courseName: 'Next.js - The Complete Guide',
        tutor: 'Maximilian Schwarzmüller',
        duration: '30 hours',
        level: 'Beginner to Advanced',
        description: 'Master Next.js with App Router, React Server Components, and deployment.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/Sklc_fQBmcs',
        externalUrl: 'https://www.udemy.com/course/nextjs-react-the-complete-guide/',
        thumbnail: 'https://img.youtube.com/vi/Sklc_fQBmcs/maxresdefault.jpg',
        rating: 4.9,
        students: '150K+',
        language: 'English',
        paid: true
    },
    {
        id: 43,
        category: courseCategories.nextjs,
        courseName: 'Next.js 14 Crash Course',
        tutor: 'Traversy Media',
        duration: '2.5 hours',
        level: 'Intermediate',
        description: 'Quick introduction to Next.js 14 with App Router and server components.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/Y6KDk5iyrYE',
        externalUrl: 'https://www.youtube.com/watch?v=Y6KDk5iyrYE',
        thumbnail: 'https://img.youtube.com/vi/Y6KDk5iyrYE/maxresdefault.jpg',
        rating: 4.8,
        students: '200K+',
        language: 'English',
        paid: false
    },
    {
        id: 44,
        category: courseCategories.nextjs,
        courseName: 'Next.js Authentication',
        tutor: 'Lee Robinson',
        duration: '2 hours',
        level: 'Advanced',
        description: 'Implement authentication in Next.js with NextAuth.js and middleware.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/jHrjnEvmPtI',
        externalUrl: 'https://www.youtube.com/watch?v=jHrjnEvmPtI',
        thumbnail: 'https://img.youtube.com/vi/jHrjnEvmPtI/maxresdefault.jpg',
        rating: 4.8,
        students: '100K+',
        language: 'English',
        paid: false
    },

    // Flask Courses (4 courses)
    {
        id: 45,
        category: courseCategories.flask,
        courseName: 'Flask Full Course',
        tutor: 'Corey Schafer',
        duration: '5 hours',
        level: 'Beginner to Intermediate',
        description: 'Learn Flask from basics to building REST APIs and web applications.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/Qr4QMBUPxWo',
        externalUrl: 'https://www.youtube.com/watch?v=Qr4QMBUPxWo',
        thumbnail: 'https://img.youtube.com/vi/Qr4QMBUPxWo/maxresdefault.jpg',
        rating: 4.9,
        students: '1M+',
        language: 'English',
        paid: false
    },
    {
        id: 46,
        category: courseCategories.flask,
        courseName: 'REST APIs with Flask',
        tutor: 'Jose Salvatierra',
        duration: '12 hours',
        level: 'Intermediate',
        description: 'Build professional REST APIs with Flask, SQLAlchemy, and authentication.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/3mwFC4SHY-Y',
        externalUrl: 'https://www.udemy.com/course/rest-api-flask-and-python/',
        thumbnail: 'https://img.youtube.com/vi/3mwFC4SHY-Y/maxresdefault.jpg',
        rating: 4.7,
        students: '100K+',
        language: 'English',
        paid: true
    },
    {
        id: 47,
        category: courseCategories.flask,
        courseName: 'Flask Mega-Tutorial',
        tutor: 'Miguel Grinberg',
        duration: '15 hours',
        level: 'Intermediate to Advanced',
        description: 'Complete Flask tutorial covering databases, authentication, and deployment.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/9MHYHgh4JnY',
        externalUrl: 'https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world',
        thumbnail: 'https://img.youtube.com/vi/9MHYHgh4JnY/maxresdefault.jpg',
        rating: 4.9,
        students: '500K+',
        language: 'English',
        paid: false
    },
    {
        id: 48,
        category: courseCategories.flask,
        courseName: 'Flask with Databases',
        tutor: 'Pretty Printed',
        duration: '4 hours',
        level: 'Intermediate',
        description: 'Working with SQLAlchemy, migrations, and database design in Flask.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/cYWiDiIUxQc',
        externalUrl: 'https://www.youtube.com/watch?v=cYWiDiIUxQc',
        thumbnail: 'https://img.youtube.com/vi/cYWiDiIUxQc/maxresdefault.jpg',
        rating: 4.7,
        students: '150K+',
        language: 'English',
        paid: false
    },

    // Django Courses (5 courses)
    {
        id: 49,
        category: courseCategories.django,
        courseName: 'Django Full Course',
        tutor: 'Corey Schafer',
        duration: '7 hours',
        level: 'Beginner to Intermediate',
        description: 'Complete Django web framework course with real-world projects.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/UmljXZIypDc',
        externalUrl: 'https://www.youtube.com/watch?v=UmljXZIypDc',
        thumbnail: 'https://img.youtube.com/vi/UmljXZIypDc/maxresdefault.jpg',
        rating: 4.9,
        students: '1.5M+',
        language: 'English',
        paid: false
    },
    {
        id: 50,
        category: courseCategories.django,
        courseName: 'Django Masterclass',
        tutor: 'Maximilian Schwarzmüller',
        duration: '30 hours',
        level: 'Intermediate to Advanced',
        description: 'Build advanced web applications with Django, Django REST Framework, and more.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/OVTXbZnTpD8',
        externalUrl: 'https://www.udemy.com/course/python-django-the-practical-guide/',
        thumbnail: 'https://img.youtube.com/vi/OVTXbZnTpD8/maxresdefault.jpg',
        rating: 4.8,
        students: '150K+',
        language: 'English',
        paid: true
    },
    {
        id: 51,
        category: courseCategories.django,
        courseName: 'Django REST Framework',
        tutor: 'Bobby Stearman',
        duration: '6 hours',
        level: 'Intermediate',
        description: 'Build robust REST APIs with Django REST Framework.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/c708Nf0cHrs',
        externalUrl: 'https://www.youtube.com/watch?v=c708Nf0cHrs',
        thumbnail: 'https://img.youtube.com/vi/c708Nf0cHrs/maxresdefault.jpg',
        rating: 4.8,
        students: '300K+',
        language: 'English',
        paid: false
    },
    {
        id: 52,
        category: courseCategories.django,
        courseName: 'Django Authentication',
        tutor: 'Dennis Ivy',
        duration: '3 hours',
        level: 'Intermediate',
        description: 'Implement authentication, registration, and user profiles in Django.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/tUqUdu0Sjyc',
        externalUrl: 'https://www.youtube.com/watch?v=tUqUdu0Sjyc',
        thumbnail: 'https://img.youtube.com/vi/tUqUdu0Sjyc/maxresdefault.jpg',
        rating: 4.7,
        students: '200K+',
        language: 'English',
        paid: false
    },
    {
        id: 53,
        category: courseCategories.django,
        courseName: 'Django E-commerce Project',
        tutor: 'freeCodeCamp',
        duration: '8 hours',
        level: 'Advanced',
        description: 'Build a complete e-commerce website with Django.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/YZvRrldjf1Y',
        externalUrl: 'https://www.youtube.com/watch?v=YZvRrldjf1Y',
        thumbnail: 'https://img.youtube.com/vi/YZvRrldjf1Y/maxresdefault.jpg',
        rating: 4.8,
        students: '400K+',
        language: 'English',
        paid: false
    },

    // FastAPI Courses (3 courses)
    {
        id: 54,
        category: courseCategories.fastapi,
        courseName: 'FastAPI Full Course',
        tutor: 'Bitfumes',
        duration: '4 hours',
        level: 'Intermediate',
        description: 'Learn FastAPI, the modern Python web framework for building APIs.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/7t2alSnE2-I',
        externalUrl: 'https://www.youtube.com/watch?v=7t2alSnE2-I',
        thumbnail: 'https://img.youtube.com/vi/7t2alSnE2-I/maxresdefault.jpg',
        rating: 4.7,
        students: '300K+',
        language: 'English',
        paid: false
    },
    {
        id: 55,
        category: courseCategories.fastapi,
        courseName: 'FastAPI Masterclass',
        tutor: 'TestDriven.io',
        duration: '8 hours',
        level: 'Advanced',
        description: 'Build production-ready APIs with FastAPI, Docker, and async SQLAlchemy.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/0sOvCWFmrtA',
        externalUrl: 'https://testdriven.io/courses/tdd-fastapi/',
        thumbnail: 'https://img.youtube.com/vi/0sOvCWFmrtA/maxresdefault.jpg',
        rating: 4.9,
        students: '50K+',
        language: 'English',
        paid: true
    },
    {
        id: 56,
        category: courseCategories.fastapi,
        courseName: 'FastAPI with SQLAlchemy & PostgreSQL',
        tutor: 'Ssali Jonathan',
        duration: '3 hours',
        level: 'Intermediate',
        description: 'Build a REST API with FastAPI, SQLAlchemy, and PostgreSQL from scratch.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/t2cegpws3u',
        externalUrl: 'https://www.youtube.com/c/SsaliJonathan/',
        thumbnail: 'https://img.youtube.com/vi/t2cegpws3u/maxresdefault.jpg',
        rating: 4.7,
        students: '100K+',
        language: 'English',
        paid: false
    },

    // Go Language Courses (4 courses)
    {
        id: 57,
        category: courseCategories.go,
        courseName: 'Go Full Course',
        tutor: 'TechWorld with Nana',
        duration: '6 hours',
        level: 'Beginner to Intermediate',
        description: 'Complete Golang course covering fundamentals to building web services.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/yyUHQIec83I',
        externalUrl: 'https://www.youtube.com/watch?v=yyUHQIec83I',
        thumbnail: 'https://img.youtube.com/vi/yyUHQIec83I/maxresdefault.jpg',
        rating: 4.9,
        students: '500K+',
        language: 'English',
        paid: false
    },
    {
        id: 58,
        category: courseCategories.go,
        courseName: 'Go - The Complete Guide',
        tutor: 'Maximilian Schwarzmüller',
        duration: '25 hours',
        level: 'Beginner to Advanced',
        description: 'Master Go with concurrency, APIs, and microservices.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/2KmHtgtEZ1s',
        externalUrl: 'https://www.udemy.com/course/go-the-complete-guide/',
        thumbnail: 'https://img.youtube.com/vi/2KmHtgtEZ1s/maxresdefault.jpg',
        rating: 4.8,
        students: '80K+',
        language: 'English',
        paid: true
    },
    {
        id: 59,
        category: courseCategories.go,
        courseName: 'Go Concurrency',
        tutor: 'freeCodeCamp',
        duration: '3 hours',
        level: 'Advanced',
        description: 'Deep dive into goroutines, channels, and concurrent patterns in Go.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/LvgVSSpwND8',
        externalUrl: 'https://www.youtube.com/watch?v=LvgVSSpwND8',
        thumbnail: 'https://img.youtube.com/vi/LvgVSSpwND8/maxresdefault.jpg',
        rating: 4.8,
        students: '150K+',
        language: 'English',
        paid: false
    },
    {
        id: 60,
        category: courseCategories.go,
        courseName: 'Building REST APIs with Go',
        tutor: 'Nic Jackson',
        duration: '4 hours',
        level: 'Intermediate',
        description: 'Build production-ready REST APIs with Go and MongoDB.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/W5b64DXeP0o',
        externalUrl: 'https://www.youtube.com/watch?v=W5b64DXeP0o',
        thumbnail: 'https://img.youtube.com/vi/W5b64DXeP0o/maxresdefault.jpg',
        rating: 4.7,
        students: '120K+',
        language: 'English',
        paid: false
    },

    // Rust Courses (3 courses)
    {
        id: 61,
        category: courseCategories.rust,
        courseName: 'Rust Full Course',
        tutor: 'freeCodeCamp',
        duration: '12 hours',
        level: 'Beginner to Intermediate',
        description: 'Complete Rust programming course covering ownership, traits, and concurrency.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/BpPEoZW5IiY',
        externalUrl: 'https://www.youtube.com/watch?v=BpPEoZW5IiY',
        thumbnail: 'https://img.youtube.com/vi/BpPEoZW5IiY/maxresdefault.jpg',
        rating: 4.9,
        students: '400K+',
        language: 'English',
        paid: false
    },
    {
        id: 62,
        category: courseCategories.rust,
        courseName: 'Rust Programming Masterclass',
        tutor: 'Udemy',
        duration: '20 hours',
        level: 'Intermediate to Advanced',
        description: 'Master systems programming with Rust.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/ygL_xcavzQ4',
        externalUrl: 'https://www.udemy.com/course/rust-programming-master-class/',
        thumbnail: 'https://img.youtube.com/vi/ygL_xcavzQ4/maxresdefault.jpg',
        rating: 4.7,
        students: '50K+',
        language: 'English',
        paid: true
    },
    {
        id: 63,
        category: courseCategories.rust,
        courseName: 'Rust Web Development',
        tutor: 'Jeremy Chone',
        duration: '5 hours',
        level: 'Advanced',
        description: 'Build web applications and APIs with Rust frameworks.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/XBt9fcUqNlU',
        externalUrl: 'https://www.youtube.com/watch?v=XBt9fcUqNlU',
        thumbnail: 'https://img.youtube.com/vi/XBt9fcUqNlU/maxresdefault.jpg',
        rating: 4.8,
        students: '80K+',
        language: 'English',
        paid: false
    },

    // Java Courses (4 courses)
    {
        id: 64,
        category: courseCategories.java,
        courseName: 'Java Full Course',
        tutor: 'Code with Mosh',
        duration: '8 hours',
        level: 'Beginner',
        description: 'Learn Java programming from scratch with practical examples.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/eIrMbAQSU34',
        externalUrl: 'https://www.youtube.com/watch?v=eIrMbAQSU34',
        thumbnail: 'https://img.youtube.com/vi/eIrMbAQSU34/maxresdefault.jpg',
        rating: 4.8,
        students: '1M+',
        language: 'English',
        paid: false
    },
    {
        id: 65,
        category: courseCategories.java,
        courseName: 'Java Masterclass',
        tutor: 'Tim Buchalka',
        duration: '80 hours',
        level: 'Beginner to Advanced',
        description: 'Most comprehensive Java course covering everything from basics to advanced.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/2DrLWFzMUr8',
        externalUrl: 'https://www.udemy.com/course/java-the-complete-java-developer-course/',
        thumbnail: 'https://img.youtube.com/vi/2DrLWFzMUr8/maxresdefault.jpg',
        rating: 4.9,
        students: '500K+',
        language: 'English',
        paid: true
    },
    {
        id: 66,
        category: courseCategories.java,
        courseName: 'Data Structures in Java',
        tutor: 'freeCodeCamp',
        duration: '6 hours',
        level: 'Intermediate',
        description: 'Master data structures and algorithms implementation in Java.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/8MmMm2-kJV8',
        externalUrl: 'https://www.youtube.com/watch?v=8MmMm2-kJV8',
        thumbnail: 'https://img.youtube.com/vi/8MmMm2-kJV8/maxresdefault.jpg',
        rating: 4.8,
        students: '300K+',
        language: 'English',
        paid: false
    },
    {
        id: 67,
        category: courseCategories.java,
        courseName: 'Java Multithreading',
        tutor: 'Cave of Programming',
        duration: '4 hours',
        level: 'Advanced',
        description: 'Deep dive into concurrency and multithreading in Java.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/YdlnEWC-7Wo',
        externalUrl: 'https://www.youtube.com/watch?v=YdlnEWC-7Wo',
        thumbnail: 'https://img.youtube.com/vi/YdlnEWC-7Wo/maxresdefault.jpg',
        rating: 4.7,
        students: '200K+',
        language: 'English',
        paid: false
    },

    // Spring Boot Courses (4 courses)
    {
        id: 68,
        category: courseCategories.spring,
        courseName: 'Spring Boot Full Course',
        tutor: 'Java Brains',
        duration: '10 hours',
        level: 'Intermediate',
        description: 'Build microservices and REST APIs with Spring Boot.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/msXL2oDexqw',
        externalUrl: 'https://www.youtube.com/watch?v=msXL2oDexqw',
        thumbnail: 'https://img.youtube.com/vi/msXL2oDexqw/maxresdefault.jpg',
        rating: 4.9,
        students: '600K+',
        language: 'English',
        paid: false
    },
    {
        id: 69,
        category: courseCategories.spring,
        courseName: 'Spring Boot Masterclass',
        tutor: 'in28minutes',
        duration: '25 hours',
        level: 'Beginner to Advanced',
        description: 'Master Spring Boot, Spring Data JPA, and Spring Security.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/9SGDpanrc8U',
        externalUrl: 'https://www.udemy.com/course/spring-spring-boot-jpa-hibernate-zero-to-master/',
        thumbnail: 'https://img.youtube.com/vi/9SGDpanrc8U/maxresdefault.jpg',
        rating: 4.8,
        students: '200K+',
        language: 'English',
        paid: true
    },
    {
        id: 70,
        category: courseCategories.spring,
        courseName: 'Spring Security',
        tutor: 'Daily Code Buffer',
        duration: '5 hours',
        level: 'Advanced',
        description: 'Implement authentication and authorization with Spring Security.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/sm-8qfMWEV8',
        externalUrl: 'https://www.youtube.com/watch?v=sm-8qfMWEV8',
        thumbnail: 'https://img.youtube.com/vi/sm-8qfMWEV8/maxresdefault.jpg',
        rating: 4.8,
        students: '150K+',
        language: 'English',
        paid: false
    },
    {
        id: 71,
        category: courseCategories.spring,
        courseName: 'Spring Microservices',
        tutor: 'Java Techie',
        duration: '6 hours',
        level: 'Advanced',
        description: 'Build microservices architecture with Spring Cloud.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/BnKnT1gM3b4',
        externalUrl: 'https://www.youtube.com/watch?v=BnKnT1gM3b4',
        thumbnail: 'https://img.youtube.com/vi/BnKnT1gM3b4/maxresdefault.jpg',
        rating: 4.7,
        students: '120K+',
        language: 'English',
        paid: false
    },

    // C# & .NET Courses (4 courses)
    {
        id: 72,
        category: courseCategories.csharp,
        courseName: 'C# Full Course',
        tutor: 'freeCodeCamp',
        duration: '6 hours',
        level: 'Beginner',
        description: 'Complete C# programming course for beginners.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/GhQdlIFylQ8',
        externalUrl: 'https://www.youtube.com/watch?v=GhQdlIFylQ8',
        thumbnail: 'https://img.youtube.com/vi/GhQdlIFylQ8/maxresdefault.jpg',
        rating: 4.8,
        students: '800K+',
        language: 'English',
        paid: false
    },
    {
        id: 73,
        category: courseCategories.csharp,
        courseName: '.NET Core Full Course',
        tutor: 'Programming with Mosh',
        duration: '7 hours',
        level: 'Intermediate',
        description: 'Build web applications with .NET Core MVC and Entity Framework.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/fmvcAzHpsk8',
        externalUrl: 'https://www.youtube.com/watch?v=fmvcAzHpsk8',
        thumbnail: 'https://img.youtube.com/vi/fmvcAzHpsk8/maxresdefault.jpg',
        rating: 4.8,
        students: '400K+',
        language: 'English',
        paid: false
    },
    {
        id: 74,
        category: courseCategories.csharp,
        courseName: 'C# Masterclass',
        tutor: 'Kudvenkat',
        duration: '40 hours',
        level: 'Beginner to Advanced',
        description: 'Most comprehensive C# and .NET course.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/YT8s-90oDC0',
        externalUrl: 'https://www.udemy.com/course/csharp-tutorial-for-beginners/',
        thumbnail: 'https://img.youtube.com/vi/YT8s-90oDC0/maxresdefault.jpg',
        rating: 4.9,
        students: '250K+',
        language: 'English',
        paid: true
    },
    {
        id: 75,
        category: courseCategories.csharp,
        courseName: 'ASP.NET Core Full Course for Beginners',
        tutor: 'Julio Casal',
        duration: '5 hours',
        level: 'Intermediate',
        description: 'Build a complete REST API backend with ASP.NET Core, Entity Framework, and C#.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/AhAxLiGC7Pc',
        externalUrl: 'https://www.youtube.com/watch?v=AhAxLiGC7Pc',
        thumbnail: 'https://img.youtube.com/vi/AhAxLiGC7Pc/maxresdefault.jpg',
        rating: 4.7,
        students: '150K+',
        language: 'English',
        paid: false
    },

    // PHP Courses (3 courses)
    {
        id: 76,
        category: courseCategories.php,
        courseName: 'PHP Full Course',
        tutor: 'Giraffe Academy',
        duration: '4.5 hours',
        level: 'Beginner',
        description: 'Complete PHP programming course covering variables, arrays, OOP, and web development basics.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/OK_JCtrrv-c',
        externalUrl: 'https://www.youtube.com/watch?v=OK_JCtrrv-c',
        thumbnail: 'https://img.youtube.com/vi/OK_JCtrrv-c/maxresdefault.jpg',
        rating: 4.8,
        students: '1M+',
        language: 'English',
        paid: false
    },
    {
        id: 77,
        category: courseCategories.php,
        courseName: 'PHP OOP Masterclass',
        tutor: 'The Net Ninja',
        duration: '6 hours',
        level: 'Intermediate',
        description: 'Master object-oriented programming in PHP.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/Anz0ArcQ5kI',
        externalUrl: 'https://www.youtube.com/watch?v=Anz0ArcQ5kI',
        thumbnail: 'https://img.youtube.com/vi/Anz0ArcQ5kI/maxresdefault.jpg',
        rating: 4.8,
        students: '350K+',
        language: 'English',
        paid: false
    },
    {
        id: 78,
        category: courseCategories.php,
        courseName: 'PHP with MySQL',
        tutor: 'Dani Krossing',
        duration: '5 hours',
        level: 'Intermediate',
        description: 'Build dynamic websites with PHP and MySQL.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/BcGAPkjt_IE',
        externalUrl: 'https://www.youtube.com/watch?v=BcGAPkjt_IE',
        thumbnail: 'https://img.youtube.com/vi/BcGAPkjt_IE/maxresdefault.jpg',
        rating: 4.7,
        students: '400K+',
        language: 'English',
        paid: false
    },

    // Flutter Courses (4 courses)
    {
        id: 79,
        category: courseCategories.flutter,
        courseName: 'Flutter Full Course',
        tutor: 'freeCodeCamp',
        duration: '12 hours',
        level: 'Beginner to Intermediate',
        description: 'Build cross-platform mobile apps with Flutter.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/VPvVD8t02U8',
        externalUrl: 'https://www.youtube.com/watch?v=VPvVD8t02U8',
        thumbnail: 'https://img.youtube.com/vi/VPvVD8t02U8/maxresdefault.jpg',
        rating: 4.9,
        students: '1.2M+',
        language: 'English',
        paid: false
    },
    {
        id: 80,
        category: courseCategories.flutter,
        courseName: 'Flutter Masterclass',
        tutor: 'Maximilian Schwarzmüller',
        duration: '35 hours',
        level: 'Beginner to Advanced',
        description: 'Complete Flutter course with Firebase and state management.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/x0uinJvhNxI',
        externalUrl: 'https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/',
        thumbnail: 'https://img.youtube.com/vi/x0uinJvhNxI/maxresdefault.jpg',
        rating: 4.9,
        students: '300K+',
        language: 'English',
        paid: true
    },
    {
        id: 81,
        category: courseCategories.flutter,
        courseName: 'Flutter with Firebase',
        tutor: 'The Net Ninja',
        duration: '6 hours',
        level: 'Intermediate',
        description: 'Integrate Firebase with Flutter for backend services.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/qJq9ZMB2Ve8',
        externalUrl: 'https://www.youtube.com/watch?v=qJq9ZMB2Ve8',
        thumbnail: 'https://img.youtube.com/vi/qJq9ZMB2Ve8/maxresdefault.jpg',
        rating: 4.8,
        students: '250K+',
        language: 'English',
        paid: false
    },
    {
        id: 82,
        category: courseCategories.flutter,
        courseName: 'Flutter State Management',
        tutor: 'Flutter Mapp',
        duration: '4 hours',
        level: 'Intermediate',
        description: 'Master state management in Flutter with Provider, Bloc, and GetX.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/5vCkM9v5_9M',
        externalUrl: 'https://www.youtube.com/watch?v=5vCkM9v5_9M',
        thumbnail: 'https://img.youtube.com/vi/5vCkM9v5_9M/maxresdefault.jpg',
        rating: 4.7,
        students: '150K+',
        language: 'English',
        paid: false
    },

    // React Native Courses (3 courses)
    {
        id: 83,
        category: courseCategories.reactNative,
        courseName: 'React Native Full Course',
        tutor: 'Code with Mosh',
        duration: '8 hours',
        level: 'Intermediate',
        description: 'Build mobile apps with React Native from scratch.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/0-S5a0eXPoc',
        externalUrl: 'https://www.youtube.com/watch?v=0-S5a0eXPoc',
        thumbnail: 'https://img.youtube.com/vi/0-S5a0eXPoc/maxresdefault.jpg',
        rating: 4.8,
        students: '600K+',
        language: 'English',
        paid: false
    },
    {
        id: 84,
        category: courseCategories.reactNative,
        courseName: 'React Native - The Complete Guide',
        tutor: 'Maximilian Schwarzmüller',
        duration: '30 hours',
        level: 'Beginner to Advanced',
        description: 'Master React Native with hooks, navigation, and Redux.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/VozPNrt-LfE',
        externalUrl: 'https://www.udemy.com/course/react-native-the-practical-guide/',
        thumbnail: 'https://img.youtube.com/vi/VozPNrt-LfE/maxresdefault.jpg',
        rating: 4.9,
        students: '200K+',
        language: 'English',
        paid: true
    },
    {
        id: 85,
        category: courseCategories.reactNative,
        courseName: 'React Native with Expo',
        tutor: 'The Net Ninja',
        duration: '5 hours',
        level: 'Intermediate',
        description: 'Build and deploy React Native apps with Expo.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/mJ3bGvy0WAY',
        externalUrl: 'https://www.youtube.com/watch?v=mJ3bGvy0WAY',
        thumbnail: 'https://img.youtube.com/vi/mJ3bGvy0WAY/maxresdefault.jpg',
        rating: 4.8,
        students: '180K+',
        language: 'English',
        paid: false
    },

    // Machine Learning Courses (5 courses)
    {
        id: 86,
        category: courseCategories.machineLearning,
        courseName: 'Machine Learning Full Course',
        tutor: 'freeCodeCamp',
        duration: '10 hours',
        level: 'Beginner to Intermediate',
        description: 'Learn machine learning with Python and scikit-learn.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/NWONeJKn6kc',
        externalUrl: 'https://www.youtube.com/watch?v=NWONeJKn6kc',
        thumbnail: 'https://img.youtube.com/vi/NWONeJKn6kc/maxresdefault.jpg',
        rating: 4.9,
        students: '1.5M+',
        language: 'English',
        paid: false
    },
    {
        id: 87,
        category: courseCategories.machineLearning,
        courseName: 'Machine Learning Specialization',
        tutor: 'Andrew Ng',
        duration: '60 hours',
        level: 'Intermediate',
        description: 'Stanford\'s legendary machine learning course.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/jGwO_UgTS7I',
        externalUrl: 'https://www.coursera.org/specializations/machine-learning-introduction',
        thumbnail: 'https://img.youtube.com/vi/jGwO_UgTS7I/maxresdefault.jpg',
        rating: 4.9,
        students: '3M+',
        language: 'English',
        paid: true
    },
    {
        id: 88,
        category: courseCategories.machineLearning,
        courseName: 'Deep Learning Specialization',
        tutor: 'Andrew Ng',
        duration: '80 hours',
        level: 'Advanced',
        description: 'Master deep learning with neural networks and TensorFlow.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/CS4cs9xVecg',
        externalUrl: 'https://www.coursera.org/specializations/deep-learning',
        thumbnail: 'https://img.youtube.com/vi/CS4cs9xVecg/maxresdefault.jpg',
        rating: 4.9,
        students: '2M+',
        language: 'English',
        paid: true
    },
    {
        id: 89,
        category: courseCategories.machineLearning,
        courseName: 'PyTorch for Deep Learning',
        tutor: 'freeCodeCamp',
        duration: '8 hours',
        level: 'Intermediate',
        description: 'Learn deep learning with PyTorch.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/V_xro1bcAuA',
        externalUrl: 'https://www.youtube.com/watch?v=V_xro1bcAuA',
        thumbnail: 'https://img.youtube.com/vi/V_xro1bcAuA/maxresdefault.jpg',
        rating: 4.8,
        students: '400K+',
        language: 'English',
        paid: false
    },
    {
        id: 90,
        category: courseCategories.machineLearning,
        courseName: 'TensorFlow Full Course',
        tutor: 'Tech With Tim',
        duration: '6 hours',
        level: 'Intermediate',
        description: 'Complete TensorFlow course for machine learning.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/tPYj3fFJGjk',
        externalUrl: 'https://www.youtube.com/watch?v=tPYj3fFJGjk',
        thumbnail: 'https://img.youtube.com/vi/tPYj3fFJGjk/maxresdefault.jpg',
        rating: 4.8,
        students: '350K+',
        language: 'English',
        paid: false
    },

    // Docker & Kubernetes Courses (4 courses)
    {
        id: 91,
        category: courseCategories.docker,
        courseName: 'Docker Full Course',
        tutor: 'TechWorld with Nana',
        duration: '4 hours',
        level: 'Beginner to Intermediate',
        description: 'Learn Docker from scratch with hands-on projects.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/3c-iBn73dDE',
        externalUrl: 'https://www.youtube.com/watch?v=3c-iBn73dDE',
        thumbnail: 'https://img.youtube.com/vi/3c-iBn73dDE/maxresdefault.jpg',
        rating: 4.9,
        students: '800K+',
        language: 'English',
        paid: false
    },
    {
        id: 92,
        category: courseCategories.docker,
        courseName: 'Kubernetes Full Course',
        tutor: 'TechWorld with Nana',
        duration: '5 hours',
        level: 'Intermediate',
        description: 'Master Kubernetes for container orchestration.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/X48VuDVv0do',
        externalUrl: 'https://www.youtube.com/watch?v=X48VuDVv0do',
        thumbnail: 'https://img.youtube.com/vi/X48VuDVv0do/maxresdefault.jpg',
        rating: 4.9,
        students: '600K+',
        language: 'English',
        paid: false
    },
    {
        id: 93,
        category: courseCategories.docker,
        courseName: 'Docker and Kubernetes Masterclass',
        tutor: 'Bret Fisher',
        duration: '20 hours',
        level: 'Beginner to Advanced',
        description: 'Complete DevOps course with Docker and Kubernetes.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/Wf2eSG3owoA',
        externalUrl: 'https://www.udemy.com/course/docker-mastery/',
        thumbnail: 'https://img.youtube.com/vi/Wf2eSG3owoA/maxresdefault.jpg',
        rating: 4.9,
        students: '150K+',
        language: 'English',
        paid: true
    },
    {
        id: 94,
        category: courseCategories.docker,
        courseName: 'Kubernetes in Production',
        tutor: 'freeCodeCamp',
        duration: '6 hours',
        level: 'Advanced',
        description: 'Deploy and manage production Kubernetes clusters.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/d6WC5n9G_sM',
        externalUrl: 'https://www.youtube.com/watch?v=d6WC5n9G_sM',
        thumbnail: 'https://img.youtube.com/vi/d6WC5n9G_sM/maxresdefault.jpg',
        rating: 4.8,
        students: '200K+',
        language: 'English',
        paid: false
    },

    // AWS & Cloud Courses (4 courses)
    {
        id: 95,
        category: courseCategories.aws,
        courseName: 'AWS Full Course',
        tutor: 'freeCodeCamp',
        duration: '10 hours',
        level: 'Beginner to Intermediate',
        description: 'Complete AWS course covering EC2, S3, Lambda, and more.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/k1RI5locZE4',
        externalUrl: 'https://www.youtube.com/watch?v=k1RI5locZE4',
        thumbnail: 'https://img.youtube.com/vi/k1RI5locZE4/maxresdefault.jpg',
        rating: 4.8,
        students: '900K+',
        language: 'English',
        paid: false
    },
    {
        id: 96,
        category: courseCategories.aws,
        courseName: 'AWS Certified Solutions Architect',
        tutor: 'Adrian Cantrill',
        duration: '40 hours',
        level: 'Intermediate to Advanced',
        description: 'Prepare for AWS Solutions Architect certification.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/Ia-UEYYR44s',
        externalUrl: 'https://learn.cantrill.io/',
        thumbnail: 'https://img.youtube.com/vi/Ia-UEYYR44s/maxresdefault.jpg',
        rating: 4.9,
        students: '200K+',
        language: 'English',
        paid: true
    },
    {
        id: 97,
        category: courseCategories.aws,
        courseName: 'AWS Lambda and Serverless',
        tutor: 'freeCodeCamp',
        duration: '5 hours',
        level: 'Intermediate',
        description: 'Build serverless applications with AWS Lambda.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/e8hZ_4Z6J0c',
        externalUrl: 'https://www.youtube.com/watch?v=e8hZ_4Z6J0c',
        thumbnail: 'https://img.youtube.com/vi/e8hZ_4Z6J0c/maxresdefault.jpg',
        rating: 4.8,
        students: '300K+',
        language: 'English',
        paid: false
    },
    {
        id: 98,
        category: courseCategories.aws,
        courseName: 'Google Cloud Platform Full Course',
        tutor: 'freeCodeCamp',
        duration: '8 hours',
        level: 'Beginner to Intermediate',
        description: 'Complete GCP course for cloud computing.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/hDn1OqU8Fd0',
        externalUrl: 'https://www.youtube.com/watch?v=hDn1OqU8Fd0',
        thumbnail: 'https://img.youtube.com/vi/hDn1OqU8Fd0/maxresdefault.jpg',
        rating: 4.8,
        students: '400K+',
        language: 'English',
        paid: false
    },

    // Databases & SQL Courses (6 courses)
    {
        id: 99,
        category: courseCategories.sql,
        courseName: 'SQL Full Course',
        tutor: 'freeCodeCamp',
        duration: '4 hours',
        level: 'Beginner',
        description: 'Learn SQL and database management from scratch with practical exercises.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/7S_tz1z_5bA',
        externalUrl: 'https://www.youtube.com/watch?v=7S_tz1z_5bA',
        thumbnail: 'https://img.youtube.com/vi/7S_tz1z_5bA/maxresdefault.jpg',
        rating: 4.8,
        students: '2M+',
        language: 'English',
        paid: false
    },
    {
        id: 100,
        category: courseCategories.sql,
        courseName: 'Advanced SQL',
        tutor: 'freeCodeCamp',
        duration: '5 hours',
        level: 'Advanced',
        description: 'Master advanced SQL queries, optimization, and database design.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/2W1wkiDbh7Q',
        externalUrl: 'https://www.youtube.com/watch?v=2W1wkiDbh7Q',
        thumbnail: 'https://img.youtube.com/vi/2W1wkiDbh7Q/maxresdefault.jpg',
        rating: 4.9,
        students: '600K+',
        language: 'English',
        paid: false
    },
    {
        id: 101,
        category: courseCategories.mongodb,
        courseName: 'MongoDB Full Course',
        tutor: 'MongoDB University',
        duration: '5 hours',
        level: 'Beginner',
        description: 'Master MongoDB, the leading NoSQL database, with hands-on projects.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/ofme2o29ngU',
        externalUrl: 'https://university.mongodb.com/',
        thumbnail: 'https://img.youtube.com/vi/ofme2o29ngU/maxresdefault.jpg',
        rating: 4.8,
        students: '500K+',
        language: 'English',
        paid: false
    },
    {
        id: 102,
        category: courseCategories.mongodb,
        courseName: 'MongoDB Advanced',
        tutor: 'The Net Ninja',
        duration: '4 hours',
        level: 'Intermediate',
        description: 'Advanced MongoDB topics including aggregation and indexing.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/2h8X0Sn3pGo',
        externalUrl: 'https://www.youtube.com/watch?v=2h8X0Sn3pGo',
        thumbnail: 'https://img.youtube.com/vi/2h8X0Sn3pGo/maxresdefault.jpg',
        rating: 4.7,
        students: '200K+',
        language: 'English',
        paid: false
    },
    {
        id: 103,
        category: courseCategories.graphql,
        courseName: 'GraphQL Full Course',
        tutor: 'freeCodeCamp',
        duration: '4 hours',
        level: 'Intermediate',
        description: 'Learn GraphQL with Apollo and React.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/ed8SzALpx1Q',
        externalUrl: 'https://www.youtube.com/watch?v=ed8SzALpx1Q',
        thumbnail: 'https://img.youtube.com/vi/ed8SzALpx1Q/maxresdefault.jpg',
        rating: 4.8,
        students: '500K+',
        language: 'English',
        paid: false
    },
    {
        id: 104,
        category: courseCategories.graphql,
        courseName: 'GraphQL with Node.js',
        tutor: 'The Net Ninja',
        duration: '5 hours',
        level: 'Intermediate',
        description: 'Build GraphQL APIs with Node.js and Apollo Server.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/7giZGFDGnkc',
        externalUrl: 'https://www.youtube.com/watch?v=7giZGFDGnkc',
        thumbnail: 'https://img.youtube.com/vi/7giZGFDGnkc/maxresdefault.jpg',
        rating: 4.8,
        students: '250K+',
        language: 'English',
        paid: false
    },

    // Git & Version Control (2 courses)
    {
        id: 105,
        category: courseCategories.git,
        courseName: 'Git Full Course',
        tutor: 'freeCodeCamp',
        duration: '1.5 hours',
        level: 'Beginner',
        description: 'Learn Git version control from basics to advanced with practical examples.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/8JJ101D3kE0',
        externalUrl: 'https://www.youtube.com/watch?v=8JJ101D3kE0',
        thumbnail: 'https://img.youtube.com/vi/8JJ101D3kE0/maxresdefault.jpg',
        rating: 4.9,
        students: '3M+',
        language: 'English',
        paid: false
    },
    {
        id: 106,
        category: courseCategories.git,
        courseName: 'Git & GitHub Masterclass',
        tutor: 'Colt Steele',
        duration: '8 hours',
        level: 'Beginner to Intermediate',
        description: 'Master Git and GitHub with real-world workflows.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/RGOj5yH7evk',
        externalUrl: 'https://www.udemy.com/course/git-and-github-bootcamp/',
        thumbnail: 'https://img.youtube.com/vi/RGOj5yH7evk/maxresdefault.jpg',
        rating: 4.9,
        students: '400K+',
        language: 'English',
        paid: true
    },

    // Cybersecurity Courses (3 courses)
    {
        id: 107,
        category: courseCategories.cybersecurity,
        courseName: 'Cybersecurity Full Course',
        tutor: 'freeCodeCamp',
        duration: '8 hours',
        level: 'Beginner',
        description: 'Complete cybersecurity course covering network security, cryptography, and more.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/nzZkKoREEGo',
        externalUrl: 'https://www.youtube.com/watch?v=nzZkKoREEGo',
        thumbnail: 'https://img.youtube.com/vi/nzZkKoREEGo/maxresdefault.jpg',
        rating: 4.8,
        students: '700K+',
        language: 'English',
        paid: false
    },
    {
        id: 108,
        category: courseCategories.cybersecurity,
        courseName: 'Ethical Hacking Course',
        tutor: 'The Cyber Mentor',
        duration: '10 hours',
        level: 'Intermediate',
        description: 'Learn ethical hacking and penetration testing.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/3Kq1MIfTWCE',
        externalUrl: 'https://www.youtube.com/watch?v=3Kq1MIfTWCE',
        thumbnail: 'https://img.youtube.com/vi/3Kq1MIfTWCE/maxresdefault.jpg',
        rating: 4.9,
        students: '500K+',
        language: 'English',
        paid: false
    },
    {
        id: 109,
        category: courseCategories.cybersecurity,
        courseName: 'Web Security Course',
        tutor: 'PortSwigger',
        duration: '6 hours',
        level: 'Advanced',
        description: 'Master web application security and bug bounty hunting.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/nzZkKoREEGo',
        externalUrl: 'https://portswigger.net/web-security',
        thumbnail: 'https://img.youtube.com/vi/nzZkKoREEGo/maxresdefault.jpg',
        rating: 4.9,
        students: '200K+',
        language: 'English',
        paid: false
    },

    // Blockchain Courses (2 courses)
    {
        id: 110,
        category: courseCategories.blockchain,
        courseName: 'Blockchain Full Course',
        tutor: 'freeCodeCamp',
        duration: '6 hours',
        level: 'Beginner',
        description: 'Learn blockchain technology and cryptocurrency fundamentals.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/qOVAbKKSH10',
        externalUrl: 'https://www.youtube.com/watch?v=qOVAbKKSH10',
        thumbnail: 'https://img.youtube.com/vi/qOVAbKKSH10/maxresdefault.jpg',
        rating: 4.8,
        students: '600K+',
        language: 'English',
        paid: false
    },
    {
        id: 111,
        category: courseCategories.blockchain,
        courseName: 'Solidity & Ethereum',
        tutor: 'Dapp University',
        duration: '8 hours',
        level: 'Intermediate',
        description: 'Build smart contracts and DApps with Solidity.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/ipwxYa-F1uY',
        externalUrl: 'https://www.youtube.com/watch?v=ipwxYa-F1uY',
        thumbnail: 'https://img.youtube.com/vi/ipwxYa-F1uY/maxresdefault.jpg',
        rating: 4.8,
        students: '300K+',
        language: 'English',
        paid: false
    },

    // Angular Courses (3 courses)
    {
        id: 112,
        category: courseCategories.angular,
        courseName: 'Angular Full Course',
        tutor: 'freeCodeCamp',
        duration: '5 hours',
        level: 'Intermediate',
        description: 'Learn Angular framework from scratch, covering components, services, routing, and RxJS.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/3qBXWUpoPHo',
        externalUrl: 'https://www.youtube.com/watch?v=3qBXWUpoPHo',
        thumbnail: 'https://img.youtube.com/vi/3qBXWUpoPHo/maxresdefault.jpg',
        rating: 4.8,
        students: '700K+',
        language: 'English',
        paid: false
    },
    {
        id: 113,
        category: courseCategories.angular,
        courseName: 'Angular Crash Course',
        tutor: 'Traversy Media',
        duration: '2 hours',
        level: 'Beginner',
        description: 'Quick introduction to Angular covering components, services, and HTTP.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/Fdf5aTYRW0E',
        externalUrl: 'https://www.youtube.com/watch?v=Fdf5aTYRW0E',
        thumbnail: 'https://img.youtube.com/vi/Fdf5aTYRW0E/maxresdefault.jpg',
        rating: 4.7,
        students: '800K+',
        language: 'English',
        paid: false
    },

    // Express.js Courses (2 courses)
    {
        id: 114,
        category: courseCategories.express,
        courseName: 'Express.js Full Course',
        tutor: 'freeCodeCamp',
        duration: '4 hours',
        level: 'Intermediate',
        description: 'Build RESTful APIs and web apps with Node.js and Express.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/G8uL0lFFoN0',
        externalUrl: 'https://www.youtube.com/watch?v=G8uL0lFFoN0',
        thumbnail: 'https://img.youtube.com/vi/G8uL0lFFoN0/maxresdefault.jpg',
        rating: 4.8,
        students: '400K+',
        language: 'English',
        paid: false
    },
    {
        id: 115,
        category: courseCategories.express,
        courseName: 'Express.js Crash Course',
        tutor: 'Traversy Media',
        duration: '1.5 hours',
        level: 'Beginner',
        description: 'Get started with Express.js quickly — routing, middleware, and REST APIs.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/L72fhGm1tfE',
        externalUrl: 'https://www.youtube.com/watch?v=L72fhGm1tfE',
        thumbnail: 'https://img.youtube.com/vi/L72fhGm1tfE/maxresdefault.jpg',
        rating: 4.8,
        students: '600K+',
        language: 'English',
        paid: false
    },

    // Data Science Courses (3 courses)
    {
        id: 116,
        category: courseCategories.dataScience,
        courseName: 'Data Science Full Course',
        tutor: 'freeCodeCamp',
        duration: '10 hours',
        level: 'Beginner to Intermediate',
        description: 'Complete data science course covering Python, statistics, Pandas, and visualization.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/ua-CiDNNj30',
        externalUrl: 'https://www.youtube.com/watch?v=ua-CiDNNj30',
        thumbnail: 'https://img.youtube.com/vi/ua-CiDNNj30/maxresdefault.jpg',
        rating: 4.8,
        students: '1M+',
        language: 'English',
        paid: false
    },
    {
        id: 117,
        category: courseCategories.dataScience,
        courseName: 'Statistics for Data Science',
        tutor: 'freeCodeCamp',
        duration: '8 hours',
        level: 'Intermediate',
        description: 'Master statistics and probability for data science and machine learning.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/xxpc-HPKN28',
        externalUrl: 'https://www.youtube.com/watch?v=xxpc-HPKN28',
        thumbnail: 'https://img.youtube.com/vi/xxpc-HPKN28/maxresdefault.jpg',
        rating: 4.7,
        students: '400K+',
        language: 'English',
        paid: false
    },
    {
        id: 118,
        category: courseCategories.dataScience,
        courseName: 'Data Science with Python',
        tutor: 'Simplilearn',
        duration: '6 hours',
        level: 'Beginner',
        description: 'Introduction to data science using Python, NumPy, Pandas, and Matplotlib.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/mkv5mxYu0Wk',
        externalUrl: 'https://www.youtube.com/watch?v=mkv5mxYu0Wk',
        thumbnail: 'https://img.youtube.com/vi/mkv5mxYu0Wk/maxresdefault.jpg',
        rating: 4.7,
        students: '500K+',
        language: 'English',
        paid: false
    },

    // Flutter Courses (2 courses)
    {
        id: 119,
        category: courseCategories.flutter,
        courseName: 'Flutter Full Course',
        tutor: 'freeCodeCamp',
        duration: '6 hours',
        level: 'Beginner to Intermediate',
        description: 'Build cross-platform mobile apps with Flutter and Dart from scratch.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/VPvVD8t02U8',
        externalUrl: 'https://www.youtube.com/watch?v=VPvVD8t02U8',
        thumbnail: 'https://img.youtube.com/vi/VPvVD8t02U8/maxresdefault.jpg',
        rating: 4.8,
        students: '600K+',
        language: 'English',
        paid: false
    },
    {
        id: 120,
        category: courseCategories.flutter,
        courseName: 'Flutter Crash Course',
        tutor: 'Traversy Media',
        duration: '2 hours',
        level: 'Beginner',
        description: 'Quick start guide to Flutter — widgets, state management, and navigation.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/1gDhl4leEzA',
        externalUrl: 'https://www.youtube.com/watch?v=1gDhl4leEzA',
        thumbnail: 'https://img.youtube.com/vi/1gDhl4leEzA/maxresdefault.jpg',
        rating: 4.7,
        students: '300K+',
        language: 'English',
        paid: false
    },

    // React Native Courses (2 courses)
    {
        id: 121,
        category: courseCategories.reactNative,
        courseName: 'React Native Full Course',
        tutor: 'JavaScript Mastery',
        duration: '8 hours',
        level: 'Intermediate',
        description: 'Build cross-platform mobile apps with React Native and Expo.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/mJ3bGvy0WAY',
        externalUrl: 'https://www.youtube.com/watch?v=mJ3bGvy0WAY',
        thumbnail: 'https://img.youtube.com/vi/mJ3bGvy0WAY/maxresdefault.jpg',
        rating: 4.8,
        students: '400K+',
        language: 'English',
        paid: false
    },
    {
        id: 122,
        category: courseCategories.reactNative,
        courseName: 'React Native Crash Course',
        tutor: 'Traversy Media',
        duration: '2 hours',
        level: 'Intermediate',
        description: 'Get started with React Native — components, navigation, and state management.',
        embedUrl: 'https://www.youtube-nocookie.com/embed/Hf4MJH0jDb4',
        externalUrl: 'https://www.youtube.com/watch?v=Hf4MJH0jDb4',
        thumbnail: 'https://img.youtube.com/vi/Hf4MJH0jDb4/maxresdefault.jpg',
        rating: 4.7,
        students: '350K+',
        language: 'English',
        paid: false
    }
];
