"""added otp_expiry

Revision ID: 119869dfacf0
Revises: 2d2e76fc7924
Create Date: 2026-03-03 23:28:00.117329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119869dfacf0'
down_revision = '2d2e76fc7924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_expiry')

    # ### end Alembic commands ###
