"""Added otp expiry column

Revision ID: 2d2e76fc7924
Revises: d949994eb4d1
Create Date: 2026-03-03 15:46:42.487564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2e76fc7924'
down_revision = 'd949994eb4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
