"""remove subject rename body to message

Revision ID: 31ef1b7098b3
Revises: 
Create Date: 2026-03-31 23:47:32.235287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ef1b7098b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.drop_column('body')
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
