"""Updated newsletter and admin_update relationships

Revision ID: 3adef4d991f7
Revises: 
Create Date: 2026-03-09 14:48:23.372776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adef4d991f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_update_recipients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_update_recipients',
    sa.Column('admin_update_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('newsletter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_update_id'], ['admin_update.id'], name=op.f('admin_update_recipients_admin_update_id_fkey')),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletter.id'], name=op.f('admin_update_recipients_newsletter_id_fkey')),
    sa.PrimaryKeyConstraint('admin_update_id', 'newsletter_id', name=op.f('admin_update_recipients_pkey'))
    )
    # ### end Alembic commands ###
